[package]
authors = ["Sascha Grunert <sgrunert@suse.com>"]
edition = "2018"
name = "gbar"
version = "0.1.0"

[dependencies]
failure = "0.1.5"
env_logger = "0.6.0"
gfx-backend-gl = { version = "0.1.0", features = ["glutin"] }
gfx-hal = "0.1.0"
glsl-to-spirv = "0.1.7"
log = "0.4.6"
wayland-client = "=0.21.10"
winit = "0.18.0"

[[bin]]
name = "gbar"
path = "src/main.rs"
